parser grammar HprimsParser;

options {

    // Default language but name it anyway
    //
    language  = Java;

    // Use the vocabulary generated by the accompanying
    // lexer. Maven knows how to work out the relationship
    // between the lexer and parser and will build the 
    // lexer before the parser. It will also rebuild the
    // parser if the lexer changes.
    //
    tokenVocab = HprimsLexer;
}

line_h
@init{System.out.println("Start");}
@after{System.out.println("End");} :
   content DELIMITER1 DELIMITER2 REPETITER ESC DELIMITER3 DELIMITER1;

 content:
   PRINTABLE*;